@url = http://localhost:8080/api/follow/

###
# happy path
GET {{url}}/followers/2 HTTP/1.1

###
# happy path
GET {{url}}/following/2 HTTP/1.1

###
# happy path
GET {{url}}/followers/1 HTTP/1.1

###
# happy path
GET {{url}}/following/1 HTTP/1.1

###
# happy path
POST {{url}}
Content-Type: application/json

{
    "id": 1,
    "follower": {
        "userId": 1,
        "username": "JoeSchmoe",
        "email": "JoeSchmoe@Test44.com",
        "password": "Password44!",
        "profilePicture": "https://rails-app-capstone.s3.us-west-1.amazonaws.com/2025-03-21/babyyoda.jpg",
        "firstName": "Joe",
        "lastName": "Schmoe",
        "city": "New York",
        "state": "NY",
        "postalCode": "10001"
        },
    "following": {
        "userId": 2,
        "username": "JohnDoe",
        "email": "JohnDoe@Test44.com",
        "password": "Password44!",
        "profilePicture": null,
        "firstName": "John",
        "lastName": "Doe",
        "city": "New York",
        "state": "NY",
        "postalCode": "10001"
    }
}

###
# happy path
DELETE {{url}}/{1} HTTP/1.1
