@url = http://localhost:8080/api/like/

###
# happy path
GET {{url}}/1 HTTP/1.1


###
# happy path
POST {{url}} HTTP/1.1
{
  "id": 1,
    "liker": {
        "userId": 1,
        "username": "JoeSchmoe",
        "email": "JoeSchmoe@Test44.com",
        "password": "Password44!",
        "profilePicture": null,
        "firstName": "Joe",
        "lastName": "Schmoe",
        "city": "New York",
        "state": "NY",
        "postalCode": "10001"
    },
    "clip": {
        "clipId": 1,
        "userProfile": {
                "userId": 1,
                "username": "JoeSchmoe",
                "email": "JoeSchmoe@Test44.com",
                "password": "Password44!",
                "profilePicture": null,
                "firstName": "Joe",
                "lastName": "Schmoe",
                "city": "New York",
                "state": "NY",
                "postalCode": "10001",
                "createdAt": "2025-03-22T13:05:11"
            },
        "mediaUrl": "https://rails-app-capstone.s3.us-west-1.amazonaws.com/2025-03-21/prod.mp4",
        "caption": "OG Yea Right"
    }
}



###
# happy path
DELETE {{url}}/{1} HTTP/1.1